# A Travis CI configuration file.

sudo: required

language: scala

services:
  - docker

notifications:
  email: false
  slack:
    on_pull_requests: false
    secure: "mXW4QBNdyn/1Ei8VvxhdA5hG12dmFdfKuNXQn2FvhukK5VgoNMYCMS5LPTZNQ39+XC9yHNpuf+1deHg7Z6Mm3XQTfHUtQ2o/1Kpmai9ko5dFpgCOXYMm9wpqxFuaZDAObliW5NUqrtK8JiZG1QYVZgWmDztgKvLZSvXPbNqm5gWQC3hAiZXobtKGevqzXoAKyXJlG1iBzxLRQ34KMu2RTV/HITJjxm1XRsrARGMsbPOc74vuEH3jm+o37FlzDU/XX2xQUtueSFq1W/uAicEKArQRZaJkcJGMUGdWRmdbHrojzn2jQAnUe2io1qeTffWKTOmsgPhWJ/vOUnLP9N4QXM7/JMcU3b0O2fi7VyZ2vDWphEpQYsgIrx3u05mXLxyQOI9yg6urRar58HH5+zv3Sr9tkLdfwFrdV1YR5PNccTmb06g3k36XrV7aAqznbEuPzRAX9jPb4GBy0JU7yzmESjTcnNkUODMjlcSLW4NtN0uKWHknvSuejOjg1z7ElDcii+uIvCCaUe2Kdb5W3OtPYOoAnOQzdnpBZqFUVJalX1Sx4orgSR2p7vUD5MYrWrgXnWHafqGkXxPUgvnGCn7YcEjM7lUHrR6uvilUFj9nWPdRH755M5cqhQgh0Tt8LVy9IMNIBlk4EeLe7afoKz7UuEmfO09I31ostKHyWvOj7K8="

install: true

before_install:
  - sudo apt-get -y update -qq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -y install docker-engine=1.11.0-0~trusty
  - docker --version
  - sudo apt-get -y install python-pip
  - pip install --user jsonschema
  - pip install --user argcomplete
  - pip install --user ansible
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
