---
# This playbook installs additional packages after whisk has been deployed.

- include: properties.yml

- hosts: ansible
  tasks:
    - include: tasks/installCatalog.yml
      when: (mode == "deploy" and catalog_source != "catalog-repos")
      
    - include: tasks/installOpenwhiskCatalog.yml
      when: (mode == "deploy" and catalog_source == "catalog-repos")
      with_dict: "{{ catalog_repos }}"