---
# This playbook deploys an Openwhisk stack.  

- hosts: ansible
  tasks:
  - name: deploy database
    local_action: shell "./wipeTransientDBs.sh" chdir="{{ playbook_dir }}/../tools/db"

- hosts: all
  roles:
  - consul

- hosts: kafka
  roles:
  - kafka

- hosts: controllers
  roles:
  - controller

- hosts: loadbalancers
  roles:
- loadbalancer

- hosts: activators
  roles:
  - activator

- hosts: invokers
  roles:
  - invoker

- hosts: edge
  roles:
  - nginx
